spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 0
      max-active: 100
      min-idle: 0
      time-between-eviction-runs-millis: 60000
      time-between-connect-error-millis: 500
      min-evictable-idle-time-millis: 1800000
      max-evictable-idle-time-millis: 25200000
  jpa:
    database: MYSQL
  web:
    resources:
      static-locations: classpath:/static,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:/dist 