spring:
  redis:
    host: localhost
    port: 6379
    password: macula@^cloud$
    database: 1
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      default-binder: rocketmq
      bindings:
        stock-out-0:
          binder: rocketmq
          group: scmp-cloud-stock
          destination: scmp-cloud-stock-topic
          content-type: application/json

    sentinel:      transport:        dashboard: localhost:9080