server:
  port: 7086
spring:
  application:
    name: scmp-cloud-stock-client
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      default-binder: rocketmq
      bindings:
        sendStockMessage-out-0:
          destination: person-event
          binder: rocketmq
        receiveStockMessage-in-0:
          binder: rocketmq
          group: scmp-cloud-stock
          destination: person-event
        receiveStockMessage2-in-0:
          binder: rocketmq
          group: scmp-cloud-stock2
          destination: person-event      function:        definition: sendStockMessage;receiveStockMessage;receiveStockMessage2
management:
  endpoint:
    health:
      show-details: ALWAYS
  server:
    port: 9086
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  pattern:
    file: "%d %file:%line %p - %m%n"
    console: "%d %file:%line %p - %m%n"
  level:
    ROOT: INFO